solr:
  image: solr
  expose:
   - "8983"
  labels:
    io.rancher.scheduler.affinity:host_label: nodetype=backend
 
thredds:
  image: km4rcus/thredds
  expose:
   - "8080"
   - "8443"
  volume_driver: convoy-nfs
  volumes:
   - ${service_name}-data:/vault
  labels:
    io.rancher.scheduler.affinity:host_label: nodetype=backend

irods-rest:
  image: km4rcus/irods-rest:4.0.2.5-rc1
  expose:
   - "8080"
  links:
   - irods
  labels:
    io.rancher.scheduler.affinity:host_label: nodetype=backend

irods:
  image: km4rcus/icat:4.1.8 
  container_name: irods
  expose:
   - "1247"
   - "20000-20199"
  hostname: irods
  command: irods
  links:
    - irods-db
    - solr
  environment:
    RODS_PASSWORD: irods
    PGPASSWORD: foobar
    ZONE: ${service_name}Zone
  volume_driver: convoy-nfs
  volumes:
    - ${service_name}-config:/etc/irods 
    - ${service_name}-data:/vault
  labels:
    io.rancher.scheduler.affinity:host_label: nodetype=backend

irods-db:
  image: postgres:9.4
  environment:
    POSTGRES_PASSWORD: foobar
  volume_driver: convoy-nfs
  volumes:
    - ${service_name}-db:/var/lib/postgresql
  labels:
    io.rancher.scheduler.affinity:host_label: nodetype=backend
